#pragma once

enum SCENEID { SC_LOGO, SC_MENU, SC_EDIT, SC_STAGE1, SC_STAGE2, SC_STAGE3, SC_ENDING, SC_END };

enum DIRECTION { DIR_LEFT, DIR_UP, DIR_RIGHT, DIR_DOWN, DIR_LT, DIR_RT, DIR_END };

enum OBJID { OBJ_PLAYER, OBJ_MONSTER, OBJ_ITEM, OBJ_END };
